Add Client resource for basic authentication
patientsknowbest/terraform-provider-aidbox pull request #28
Opened 2022-06-27 20:54 UTC by k9t5h

I have based my implementation on the following documentation: https://docs.aidbox.app/security-and-access-control-1/auth/basic-auth

Basic auth with multibox requires Client and AccessPolicy resources. I am attempting to add the former since engine _allow_ is already supported in `aidbox_access_policy`.

2022-06-28 20:05 UTC, MFAshby requested changes
thanks :D couple of minor structural issues, otherwise this looks ok. Thanks for adding tests!

Regarding type of AccessPolicy.link, yes if I have structured this incorrectly please fix it! Aidbox structure description says this
```
AccessPolicy.link | Reference [ ]
```
so I guess it means introduction of a `Reference` type

2022-06-29 07:50 UTC, k9t5h commented on internal/aidbox/auth_client.go
> +type AuthClient struct {
You are right. This was my half-baked solution for the naming collision.
(I went with Auth Client because the Aidbox UI uses it as well.)

2022-06-29 11:00 UTC, MFAshby commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
you can see it in aidbox server, go to 'Resources' then click 'structure' next to the interesting resource, you can then click on the field for even more info (it says 'string' but actually it's an enum)
![image](https://user-images.githubusercontent.com/1760515/176420809-91bb1908-ffc9-4215-ad3e-6989442d04b8.png)


![image](https://user-images.githubusercontent.com/1760515/176420908-82f3923d-99e1-47fd-82f1-33e8dbfc5121.png)


![image](https://user-images.githubusercontent.com/1760515/176421015-452c12de-21c3-4337-b19e-a24ff8d5d019.png)

2022-06-29 11:04 UTC, MFAshby commented on internal/aidbox/auth_client.go
> +type AuthClient struct {
no worries, it was a good try :D

2022-06-29 11:04 UTC, k9t5h commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
Thank you! 🙏
But isn't it an array of strings though? :D
https://docs.aidbox.app/security-and-access-control-1/overview#client

2022-06-29 11:13 UTC, MFAshby commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
it's a string-typed enum. Looks like Aidbox doesn't have a specialized `enum` type, but my screenshot there shows it is definitely a string with a limited set of values. 

By typing it correctly in Go, you'll end up with an error message at the plan stage (because the type is wrong) rather than an error at apply time (because aidbox will reject strings not in the above list)

2022-06-29 11:17 UTC, k9t5h commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
I have changed the code locally to an enum but the test throws an error:
```
`Error: unexpected status code received 422 422 Unprocessable Entity
```
The above screenshot also shows `isCollection: true`.
So I believe we do need an array, and only accept the given 7 values.

2022-06-29 11:23 UTC, MFAshby commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
sorry, I misunderstood your comment! yes it should be an array, and the array elements should be enums!

2022-06-30 07:24 UTC, k9t5h commented on internal/aidbox/auth_client.go
> +type AuthClient struct {
Renamed https://github.com/patientsknowbest/terraform-provider-aidbox/pull/28/commits/ae361f8bea71265ddac73fa5dc5b04d1f40e8935

2022-06-30 07:32 UTC, k9t5h commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
I have implemented it with enums then I found a much simpler solution with `ValidateFunc`. https://github.com/patientsknowbest/terraform-provider-aidbox/pull/28/commits/08c8418db9cc2984cf8fb01498ee0058a3e15610
https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors#validatefunc
If the wrong string is entered, we will get the following message:
```
Error: expected grant_types.0 to be one of [basic], got code
```
The enum version adds a bit of complexity to the code, and we would just comment out the other 6 types anyway because they need additional fields to work properly. So I prefer using validation. What do you think?

2022-06-30 07:36 UTC, k9t5h commented
🚧 Still not ready yet.
I need to switch to Reference [ ] in `AccessPolicy.link`.

2022-06-30 10:25 UTC, MFAshby commented on internal/provider/resource_client.go
> +				ValidateFunc: validation.StringInSlice([]string{"basic"}, false),
nb: are we only supporting `basic` clients for now? (I'm ok with it)

2022-06-30 10:26 UTC, MFAshby commented on internal/aidbox/client.go
> +	GrantTypes []interface{} `json:"grant_types"`
b: This should be an enum type

2022-06-30 10:29 UTC, MFAshby commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
ah I didn't see this reply before commenting elsewhere.

The code is separated into two parts: a generic Aidbox client library (nothing terraform specific about it) which in theory could be extracted and used in other projects, and the terraform specific parts which use that API.

Putting the validation only into the latter means the former is less useful. I'm ok with it if you really want to though, and it does indeed validate correctly.

2022-07-04 11:35 UTC, k9t5h commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
Oh I see your point now. I don't want to downgrade the existing structure, so I will stick to enums.

2022-07-08 16:29 UTC, k9t5h commented on internal/aidbox/client.go
> +	GrantTypes []interface{} `json:"grant_types"`
Fixed https://github.com/patientsknowbest/terraform-provider-aidbox/pull/28/commits/30041f4ed42130f5f48e56bd9e79cc5f5711a6f3

2022-07-08 16:29 UTC, k9t5h commented on internal/aidbox/auth_client.go
> +	GrantTypes []interface{} `json:"grant_types"`
Done https://github.com/patientsknowbest/terraform-provider-aidbox/pull/28/commits/30041f4ed42130f5f48e56bd9e79cc5f5711a6f3

2022-07-09 20:29 UTC, MFAshby approved these changes
LGTM thank you :+1:

2022-07-09 20:29 UTC, MFAshby commented on internal/provider/resource_access_policy.go
> +		data := map[string]interface{}{
nit: are `ResourceId` and `ResourceType` both `string`? In which case the map type could be more specific
```suggestion
		data := map[string]string{
```

2022-07-09 20:29 UTC, MFAshby commented on internal/provider/resource_access_policy.go
> +			Type:        schema.TypeList,
:+1: thanks for fixing!

2022-07-09 20:29 UTC, MFAshby commented on internal/provider/resource_client.go
> +	}
nb; why is this necessary?

2022-07-11 09:45 UTC, k9t5h commented on internal/provider/resource_client.go
> +	}
To avoid this error:
```
panic: grant_types.0: '' expected type 'string', got unconvertible type 'aidbox.GrantType', value: '0'
```

2022-07-11 10:02 UTC, k9t5h commented on internal/provider/resource_access_policy.go
> +		data := map[string]interface{}{
Changed here https://github.com/patientsknowbest/terraform-provider-aidbox/pull/28/commits/c19cbb007bed2baba806ef296f44c0d60ab7fe70

2022-07-11 13:31 UTC, MFAshby commented on internal/provider/resource_client.go
> +	}
ah ok!

2022-07-18 12:23 UTC, merged