Add support for SearchParameter resource
patientsknowbest/terraform-provider-aidbox pull request #69
Opened 2023-03-29 16:47 UTC by k9t5h

I have followed the Aidbox structure definition and this documentation: https://docs.aidbox.app/api-1/fhir-api/search-1/searchparameter

2023-03-29 16:48 UTC, k9t5h commented on internal/provider/resource_search_parameter.go
> +			Type:        schema.TypeList,
I intended to use TypeMap here but using the Elem block to define specific keys for the map is currently not possible.
https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#typemap

2023-03-29 16:54 UTC, k9t5h commented on internal/provider/resource_search_parameter.go
> +				Type: schema.TypeString,
Expression has a bit of complexity.

> Expression is a set of elements, by which we want to search. Expression is array of PathArrays; PathArray is an array of strings, integers or objects, where each type has special meaning:
string - name of element
integer - index in collection
object - filter by pattern in collection

However, this mixing of data types conflicts with TypeList because the items defined by the Elem property must be all of the same type.
https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#typelist

2023-03-29 17:06 UTC, k9t5h commented on internal/provider/resource_search_parameter.go
> +		if strings.Contains(ex, "|") {
But I might have got lost in the forest and overcomplicated things so I'm open to suggestions.

2023-03-30 10:08 UTC, MFAshby commented on internal/provider/resource_search_parameter.go
> +				Type: schema.TypeString,
nb: could you add this as a comment to the code? in case someone wants to know in future  :D

2023-03-30 10:09 UTC, MFAshby commented on README.md
> +$ (cd scripts && AIDBOX_LICENSE=<your-devbox-license> MB_LICENSE=<your-multibox-license> docker-compose up -d)
:pray: thank you

2023-03-30 10:12 UTC, MFAshby commented on internal/provider/resource_search_parameter.go
> +		if strings.Contains(ex, "|") {
b: I think it's a reasonable solution to the problem. I do think the documentation needs to be very clear on how this works though.

nb: Is pipe separator definitely safe to use in this case? would the field name ever have a pipe, or would the filter ever start with a pipe?

2023-03-30 10:13 UTC, MFAshby commented on internal/provider/resource_search_parameter.go
> +			// due to unmarshal in parseResource, the number becomes a float instead of int
nb: is this a bug in parseResource rather than something to handle here?

2023-03-30 10:14 UTC, MFAshby requested changes
Thanks! 

I think the 'expression' field documentation should be clear on how to add filters i.e. with the pipe separator, but otherwise lgtm. I don't have a better idea how to do this than what you have implemented :D

2023-03-30 14:35 UTC, k9t5h commented on internal/provider/resource_search_parameter.go
> +			// due to unmarshal in parseResource, the number becomes a float instead of int
added a clearer comment https://github.com/patientsknowbest/terraform-provider-aidbox/pull/69/commits/3a81feb5943c3f30b7ed72825c6e7a49b19ef80f
it's a json.Unmarshal feature

2023-03-30 14:35 UTC, k9t5h commented on internal/provider/resource_search_parameter.go
> +				Type: schema.TypeString,
done https://github.com/patientsknowbest/terraform-provider-aidbox/pull/69/commits/3a81feb5943c3f30b7ed72825c6e7a49b19ef80f

2023-03-30 14:57 UTC, k9t5h commented on internal/provider/resource_search_parameter.go
> +		if strings.Contains(ex, "|") {
Expanded the doc https://github.com/patientsknowbest/terraform-provider-aidbox/pull/69/commits/3a81feb5943c3f30b7ed72825c6e7a49b19ef80f

The pipe separator seems the safest character, and I don't believe pipe is allowed in normal naming cases, but I don't have 100% certainty over this.

2023-03-31 07:14 UTC, merged